---
# Master playbook to configure all servers
- name: Configure all servers
  ansible.builtin.import_playbook: siege.yml

- name: Configure web servers
  ansible.builtin.import_playbook: webserver.yml

- name: Configure SQL servers
  ansible.builtin.import_playbook: sqlserver.yml
